name: Automated backups

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  roam-backup:
    runs-on: ubuntu-latest
    name: Roam backup
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Backup graphs
        run: |
          mkdir -p __Roam
          cd __Roam
          git clone -q https://github.com/everruler12/roam2github.git roam2github
          cd $_
          npm install
          npm run start -s
          cd ..
          rm -rf ../Roam
          mv __Roam ../Roam
          cd ..
          rm -rf __Roam
          bash .bin/roam_asset_downloader.sh Roam/markdown/ArtOfGig
          bash .bin/roam_asset_downloader.sh Roam/markdown/Astonishing_Stories
        env:
          R2G_EMAIL: ${{ secrets.ROAM_USER }}
          R2G_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          R2G_GRAPH: ArtOfGig,Astonishing_Stories
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Roam backup
