name: Automated backups

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 9 * * *"

jobs:
  roam-backup:
    runs-on: ubuntu-latest
    name: Roam backup
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Backup graphs
        run: |
          cd /tmp
          git clone -q https://github.com/everruler12/roam2github.git roam2github
          cd $_
          npm install
          npm run start -s
          cd $GITHUB_WORKSPACE
          rm -rf Roam
          mkdir Roam
          mv {edn,json,markdown} Roam/
          echo '# Seems to be broken as of 2023-01-13: npx markdown-backup "Roam/markdown/**/*.md"'
          bash .bin/roam_asset_downloader.sh Roam/markdown/ArtOfGig
          bash .bin/roam_asset_downloader.sh Roam/markdown/Astonishing_Stories
        env:
          R2G_EMAIL: ${{ secrets.ROAM_USER }}
          R2G_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          R2G_GRAPH: ArtOfGig,Astonishing_Stories
          MD_REPLACEMENT: _
      - name: Commit changes
        uses: everruler12/git-auto-commit-action@latest
        with:
          commit_message: Automated Roam backup
